# Base 이미지
FROM node:18.4.0-alpine


# 작업 공간
RUN mkdir /app
WORKDIR /app
ADD . /app
RUN npm install -g npm@8.16.0
RUN npm install

ENV NODE_ENV production

RUN npm run build


EXPOSE 3000

# 실행 명령어
ENTRYPOINT ["npm","start"]